ci: fix the upgrade failure
Signed-off-by: nabim777 <nabinalemagar019@gmail.com>

diff --git a/.github/workflows/app-upgrade.yml b/.github/workflows/app-upgrade.yml
--- a/.github/workflows/app-upgrade.yml
+++ b/.github/workflows/app-upgrade.yml
@@ -24,6 +24,8 @@ jobs:
     steps:
       - name: Checkout
         uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd
+        with:
+          ref: ${{ inputs.branch }}
 
       - name: Create matrix
         id: create-matrix
@@ -79,6 +81,7 @@ jobs:
         uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd
         with:
           path: integration_openproject
+          ref: ${{ inputs.branch }}
       
       - name: Setup PHP ${{ format('{0}.{1}', matrix.phpVersionMajor,matrix.phpVersionMinor) }}
         uses: shivammathur/setup-php@a4e22b60bbb9c1021113f2860347b0759f66fe5d
@@ -89,13 +92,13 @@ jobs:
       
       - name: Wait for Nextcloud server to be ready
         run: |
-          if ! timeout 5m bash -c '
+          if ! timeout 8m bash -c '
             until curl -s -f http://localhost/status.php | grep '"'"'"installed":true'"'"'; do
               echo "[INFO] Waiting for server to be ready..."
-              sleep 10
+              sleep 15
             done
           '; then
-            echo "[ERROR] Server not ready within 5 minutes."
+            echo "[ERROR] Server not ready within 8 minutes."
             exit 1
           fi
 
